# Generated by Django 5.1.4 on 2025-01-13 11:59

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("PREMIUM", "Premium"),
                            ("BUSINESS", "Business"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "max_withdrawal_limit",
                    models.DecimalField(
                        decimal_places=2, default=1000.0, max_digits=20
                    ),
                ),
                ("notifications_enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("interest_rate", models.FloatField(default=10.5)),
                ("duration_months", models.PositiveIntegerField()),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("REPAID", "Repaid"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal"),
                            ("BUSINESS", "Business"),
                            ("MORTGAGE", "Mortgage"),
                        ],
                        default="PERSONAL",
                        max_length=20,
                    ),
                ),
                (
                    "payment_schedule",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "late_payment_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                    ),
                ),
                ("penalty_rate", models.FloatField(default=1.5)),
                ("approval_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["client", "status"],
                        name="Loan_loan_client__9c1780_idx",
                    )
                ],
            },
        ),
    ]
