# Generated by Django 5.1.4 on 2025-01-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Loan",
            "0002_alter_loan_approval_date_alter_loan_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
