# Generated by Django 5.1.4 on 2025-01-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Loan", "0003_loan_total_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="loan_type",
        ),
    ]
