# Generated by Django 5.1.4 on 2025-01-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Loan", "0004_remove_loan_loan_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="amount_paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
