# Generated by Django 5.1.4 on 2025-01-15 17:50

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Loan", "0005_loan_amount_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=20,
                null=True,
            ),
        ),
    ]
